services:
  workalone:
    image: workalone:latest
    container_name: workaloneApp
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://workaloneDB:3306/workalone?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: swallaby
      SPRING_DATASOURCE_PASSWORD: swallaby1234!
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - workalone-network

networks:
  workalone-network:
    name: workalone-network
    driver: bridge
