spring:
  config:
    import: application-private.yml
  application:
    name: WorkAlone_BackEnd
  profiles:
    active: prod
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

---

spring:
  sql:
    init:
      mode: always
  config:
    import: application-private.yml
  application:
    name: WorkAlone_BackEnd
  profiles:
    active: local
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false