spring:
  application:
    name: WorkAlone_BackEnd
  profiles:
    active: local
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false